### PR TITLE
Added custom and unity builtin analyzers to csproj

### PR DESCRIPTION
**Pull request by mifreundorfer**
Implements #68

### CODE REVIEW

**Comment by Chizaruu** [comment]
Could you kindly add a test analyzer to each project, or alternatively, provide an example, and I'll be happy to follow suit.

- 2021.3
- 2022.2
- 2023.1

**Comment by Chizaruu** [comment]
Also, thanks for submitting pull requests, it means a lot to me and the community! 🥳 

It's not much but I have a Contributor role in my discord, so just ping me if you join and ill give it to you.

**Comment by mifreundorfer** [comment]
I added a test analyzer to each project that generates a class and prints a warning.

The class in Test.cs also calls the generated method to verify that the analyzer is running.

I can also add the source code for the analyzer, if you want to.

**Comment by Chizaruu** [comment]
> I added a test analyzer to each project that generates a class and prints a warning.
> 
> The class in Test.cs also calls the generated method to verify that the analyzer is running.
> 
> I can also add the source code for the analyzer, if you want to.

Thank you for taking the time to add the analyzers and source code! :D

However, I ran into a small issue.
image

It's only usable after I use `dotnet build` on the TestAnalyzer.csproj. Is this intended behaviour?

**Comment by Chizaruu** [comment]
Problem solved. I just needed to change the TargetFramework to fix the issue!

I forgot to mention I changed it before I built the project. 😅

**Pull request merged**
