### PR TITLE
Fix possbile deadlock caused by not reading stdout.

### LINKED ISSUE #64: GenerateNugetJsonSourceFiles invokes dotnet with incorrect Arguments
### Current Behavior

On Windows the Process in `GenerateNugetJsonSourceFiles` invokes dotnet with `-c "dotnet build"` as arguments, which does not work, as there is no `-c` parameter in dotnet. This seems to be an artifact of calling dotnet through a shell process on Linux and MacOS.

The correct invokation would just have `build` as an argument. This begs the question as to why dotnet is invoked through a shell on Linux and MacOS in the first place.

### Reproduction / Steps To Reproduce

- Create a Unity Project on Windows and generate the Visual Studio Code Project files.
- Observe that there are no obj and bin folders being created next to the .csproj files, because `dotnet build` is not run.

### PR DESCRIPTION
**Pull request by mifreundorfer**
Redirecting and then not reading from stdout can cause a deadlock, when the stdout pipe buffer is too small.

### CODE REVIEW

**Comment by Chizaruu** [comment]
Interesting. Have any prior cases of this happening? :o

It can be for something other than this package, as I can't find much information on this issue via Google/StackOverflow.

**Comment by Chizaruu** [comment]
After some testing, the removal of `RedirectStandardOutput = true` breaks the `dotnet build` process. 

This means that obj and bin folders with their pertaining files aren't generated automatically.
image

**Comment by mifreundorfer** [comment]
> Interesting. Have any prior cases of this happening? :o
> 
> It can be for something other than this package, as I can't find much information on this issue via Google/StackOverflow.

Yes, that is why I made this patch in the first place. My Unity Project deadlocks on `Process.WaitForExit` whenever the project files are generated. You can find an example StackOveflow here, which is caused by the same issue. [https://stackoverflow.com/questions/39312934/elimininating-process-waitforexit-standardoutput-deadlock-condition](https://stackoverflow.com/questions/39312934/elimininating-process-waitforexit-standardoutput-deadlock-condition)

This will only happen if your compiler spits out enough warnings. To reproduce it, you could try to enable nullable analysis on an existing project.  It first happened to me on Linux, but on Windows the same happens, if the dotnet command is invoked correctly. Which seems to be the issue you are running into here, which is unrelated to this patch. So removing the `RedirectStandardOutput=true` setting should be just fine.

On Windows `dotnet -c "dotnet build"` is invoked, which is not a valid argument for dotnet and obviously meant for the shell invokation on Linux\MacOS. This is why you are seeing no obj and bin folders being generated on Windows. If you reduce the arguement list from `-c "dotnet build"` to just `build` it also invokes correctly on Windows and deadlocks my project.

Why do you need to invoke dotnet through the shell in the first place though? Should it not be enough to call `dotnet build` on every system? If dotnet is not in your path, either command will fail.

**Comment by mifreundorfer** [comment]
> After some testing, the removal of `RedirectStandardOutput = true` breaks the `dotnet build` process.
> 
> This means that obj and bin folders with their pertaining files aren't generated automatically. image

I have moved this to an issue #64

**Comment by Chizaruu** [comment]
I modified the code to no longer invoke shell for Windows but still for Linux/Mac.

**Comment by Chizaruu** [comment]
@mifreundorfer I'll go ahead and merge if you are happy with the changes.

**Pull request merged**
